apiVersion: apps/v1 
kind: Deployment
metadata:
   name: iotpy-deploy 
spec:
   strategy:
      type: Recreate
   selector:
      matchLabels:
         app: iotpy
   replicas: 1
   template:
      metadata:
         name: iotpy-pod
         labels:
             app: iotpy
      spec:
          containers:
             - image: openscada/iotpy:v0.3.2
               name: iotpy 
               volumeMounts:
                 - name: devices 
                   mountPath: /iot
               env:
                 - name: "IOTPY_CRYOCON_HOST" 
                   value: "cryocon-service"
                 - name: "IOTPY_MASSCALE_01_HOST" 
                   value: "mass0-service"
                 - name: "IOTPY_MASSCALE_02_HOST" 
                   value: "mass1-service"
                 - name: "IOTPY_CRYOCON_PORT"
                   value: "5000"
                 - name: "IOTPY_FLOWCTRL_HOST"
                   value: "flowctrl-service"
                 - name: "IOTPY_FLOWCTRL_PORT"
                   value: "101"
                 - name: "IOTPY_DEVICES_DIR"
                   value: "/iot/SC-Demo-Devices.git/Devices"
                 - name: "IOTPY_DEVICES_PORT"
                   value: "8085"
                 - name: "IOTPY_PROXY_PREFIX"
                   value: "iotpy"
               ports:
               - containerPort: 8085
                 protocol: TCP
               livenessProbe:
                 httpGet:
                   path: /iotpy/
                   port: 8085
                 failureThreshold: 2
                 initialDelaySeconds: 60
                 periodSeconds: 60
                 timeoutSeconds: 1
          initContainers:
             - image: xenoscopesc/git-sync:0.1__linux_amd64
               name: git-sync
               args: ["--repo=https://github.com/Physik-Institut-UZH/SC-Demo-Devices.git", "--branch=main","--one-time"]
               volumeMounts:
                  - name: devices
                    mountPath: /tmp/git
               env:
                 - name: GIT_SYNC_USERNAME
                   valueFrom:
                      secretKeyRef:
                         name: git-secret
                         key:  username
                 - name: GIT_SYNC_PASSWORD 
                   valueFrom:
                      secretKeyRef:
                         name: git-secret
                         key:  password

          volumes:
            - name: devices
              emptyDir: {}  

